# Generated by Django 4.0.6 on 2023-02-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='circular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('timeline', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='static/images/')),
            ],
        ),
    ]
