# Generated by Django 4.0.6 on 2023-02-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashrayapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circular',
            name='date',
            field=models.CharField(default=20, max_length=50),
        ),
        migrations.AddField(
            model_name='circular',
            name='day',
            field=models.CharField(default='Mon', max_length=50),
        ),
    ]
