# Generated by Django 4.0.6 on 2023-02-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashrayapp', '0002_circular_date_circular_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='circular',
            name='author',
            field=models.CharField(default='qw', max_length=50),
        ),
    ]
