# Generated by Django 4.0.6 on 2023-02-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashrayapp', '0003_circular_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circular',
            name='img',
        ),
        migrations.AddField(
            model_name='circular',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
