# Generated by Django 4.0.6 on 2023-02-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashrayapp', '0004_remove_circular_img_circular_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_phil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('interest', models.CharField(max_length=150)),
                ('experience', models.CharField(max_length=150)),
            ],
        ),
    ]
