# Generated by Django 4.0.6 on 2023-02-18 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ashrayapp', '0006_profile_phil_donations'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_phil',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
